version: '3'
services:
  livekit:
    image: livekit/livekit-server
    ports:
      - "7880:7880"  # HTTP API
      - "7881:7881"  # WebSocket
      - "7882:7882"  # RTMP
    command: --dev --node-ip=0.0.0.0
    environment:
      LIVEKIT_KEYS: "devkey: secret"
      LIVEKIT_WS_URL: "ws://localhost:7881"
      LIVEKIT_HTTP_URL: "http://localhost:7880" 